spring:
  application:
    name: "edge-server"

hystrix:
  command:
    anag-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds:
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

server:
  port: 8080

zuul:
  ignoredServices: '*'
  routes:
    anag-service: /users/**

---
spring:
    profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true
