spring:
  application:
    name: "payment-service"
  data:
    mongodb:
      host: 192.168.99.100

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

server:
  port: 0

---
spring:
    profiles: docker
  data:
    mongodb:
      host: mongodb

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
    port: 8080
