spring:
  application:
    name: "payment-service"
  data:
    mongodb:
      port: 0
  rabbitmq:
    host: 192.168.99.100

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  security:
    enabled: false

server:
  port: 0

---
spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb
      port: 27017
  rabbitmq:
    host: message-broker

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
  instance:
    preferIpAddress: true

server:
    port: 8080
